### ISSUE TITLE
How to stop the script?

### ISSUE THREAD

**Issue by rzasharifi** [simeononsecurity/FireFox-Privacy-Script#16]
Hello. Thank you for your great work. I'm using your script because the privacy is my concern! The problem with the script is, after I was started to run it on my Windows (10), Firefox hasn't work properly! For instance, many times I should be waiting for a couple of minutes and then, that site doesn't work for me, however the same site works smoothly on other browsers. My question is, how can I stop the script and restore Firefox settings without reinstall it?

Thanks again.

**Comment by simeononsecurity** [comment]
> Hello. Thank you for your great work. I'm using your script because the privacy is my concern! The problem with the script is, after I was started to run it on my Windows (10), Firefox hasn't work properly! For instance, many times I should be waiting for a couple of minutes and then, that site doesn't work for me, however the same site works smoothly on other browsers. My question is, how can I stop the script and restore Firefox settings without reinstall it?
> 
> Thanks again.

If the site breaks, it's likely because it's doing something invasive.
You have to learn when to disable extensions and when it's worth it to you to give up privacy or when you should use another browser.
A private browser is not one you use for every website.

As far as reverting, you can use a windows snapshot
or Go to the scripts and identify what files were coppied where and remove them
https://github.com/simeononsecurity/FireFox-Privacy-Script/blob/master/sos-firefoxprivacy.ps1

If you have issues figuring that out, use chatgpt

**Comment by simeononsecurity** [comment]
I've also added some removal options in the script if you check the latest readme. I've not fully tested them yet, but give them a shot and let me know. @rzasharifi

**Comment by rzasharifi** [comment]
My problem was that I couldn't download files on my laptop and the script prevented me from doing it! Last couple days I tried again and from nowhere, download function was working! I don't know how that is possible, because I literally did noting, but it works now. I appreciate for your hard work!
