### ISSUE TITLE
When I try to install script on linux console says: ***files is not a directory

### ISSUE THREAD

**Issue by grabakin** [simeononsecurity/FireFox-Privacy-Script#7]
**Describe the bug**
When I try to install script on linux console says 
cp: target '/lib/firefox/distribution/extensions/langpack-ru@firefox.mozilla.org.xpi' is not a directory
cp: target '/lib/firefox/distribution/policies.json' is not a directory
And it seems, that script doesn't apply after that.
**To Reproduce**
1.Fresh installed firefox
2.Unzipped downloaded archive in downloads
3.Write command $ cd /home/se4ph/Downloads/FireFox-Privacy-Script-master
4.Then $ sudo chmod +x ./sos-firefoxprivacy.sh
5.Then $ sudo bash ./sos-firefoxprivacy.sh
6.After previous step error shows

**Screenshots**
![image](https://github.com/simeononsecurity/FireFox-Privacy-Script/assets/71011789/efe200e9-a5ee-4f3c-a04e-5bc262112c8a)

 - OS: Linux Mint

**Comment by simeononsecurity** [comment]
The @Qu1ert I've updated the Linux script, please try it again.
Additionally, if you installed FireFox from the app store on Linux, it's likely the SNAP version of Firefox.
You'll want to install the full version of FireFox.

To uninstall the Snap version of Firefox on Ubuntu or Linux Mint, you can use the following steps:

1. Open a terminal.

2. To list the installed Snap packages and find the exact name of the Firefox Snap package, you can use the following command:

   ```bash
   snap list
   ```

   Look for the entry related to Firefox.

3. To uninstall Firefox Snap, use the following command, replacing `firefox-snap-package-name` with the actual name of the Firefox Snap package:

   ```bash
   sudo snap remove firefox-snap-package-name
   ```

   For example, if the package name is `firefox`, you would run:

   ```bash
   sudo snap remove firefox
   ```

4. After the command completes, the Snap version of Firefox should be uninstalled from your system.

Please note that if you installed the traditional version of Firefox using the package manager (apt) as mentioned in a previous response, the Snap version would be separate from that installation, and you can keep the traditional version while removing the Snap version.

### Linux Mint:

The process for Linux Mint is the same as for Ubuntu because Linux Mint is based on Ubuntu. Follow the steps outlined for Ubuntu:

1. Open a terminal.

2. Run the following commands:

    ```bash
    sudo apt update
    sudo apt install firefox
    ```

These commands will update the package information and install the Firefox browser. After the installation is complete, you can use the modified script I provided earlier to set up the required directories and copy files.
